# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: github_traffic_aggregator_development

test:
  <<: *default
  database: github_traffic_aggregator_test

production:
  <<: *default
  database: your_app_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV["DATABASE_URL"] %>
